name: GitlabSync

on:
  push:
    branches:
      - '*' # Trigger on all branches

  delete:
    branches:
      - '*' # Trigger on all branches
    

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history to ensure full sync

    - name: Push to GitLab (main) Branch
      env:
        GITLAB_TOKEN: ${{ secrets.TARGET_TOKEN }}
      run: |
        # Add GitLab as a remote
        git remote add gitlab https://oauth2:${{ secrets.TARGET_TOKEN }}@gitlab.hrz.tu-chemnitz.de/vsr/edu/planspiel/ws2425/group03-codefinity.git

        # Push to the `main` branch in GitLab
        git push gitlab HEAD:main

