name: GitlabSync

on:
  push:
    branches:
      - '*' # Trigger on all branches

  delete:
    branches:
      - '*' # Trigger on all branches
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history to ensure full sync

    # Pull latest changes from GitLab before pushing
    - name: Pull latest changes from GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.TARGET_TOKEN }}
      run: |
        git remote add gitlab https://oauth2:${{ secrets.TARGET_TOKEN }}@gitlab.hrz.tu-chemnitz.de/vsr/edu/planspiel/ws2425/group03-codefinity.git
        git fetch gitlab
        git merge gitlab/main || true # Prevent failures due to conflicts

    # Push all branches and tags to GitLab
    - name: Push to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.TARGET_TOKEN }}
      run: |
        git push gitlab --all
        git push gitlab --tags
